<a href="https://colab.research.google.com/github/Ahsrah-09/Deep-Learning/blob/main/simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow_FPU
from tensorflow.keras.preprocessing.text import one_hot
import tensorflow as tf
print(tf.__version__)

ERROR: Could not find a version that satisfies the requirement tensorflow_FPU (from versions: none)
ERROR: No matching distribution found for tensorflow_FPU
2.17.0


In [2]:
sent=['the glass of juice',
      'the glass of milk',
      'the cup of tea',
      'I am good girl',
      'I am from kurnool']

In [3]:
vsize=10000

**One-Hot Representation**

In [4]:
onehot_repr=[one_hot(words,vsize) for words in sent]


In [5]:
print(onehot_repr)

[[1207, 8541, 817, 3546], [1207, 8541, 817, 2538], [1207, 1521, 817, 9861], [3239, 7447, 715, 8917], [3239, 7447, 4740, 2039]]


**word embedding representation**

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8

In [8]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1207 8541  817 3546]
 [   0    0    0    0 1207 8541  817 2538]
 [   0    0    0    0 1207 1521  817 9861]
 [   0    0    0    0 3239 7447  715 8917]
 [   0    0    0    0 3239 7447 4740 2039]]


In [9]:
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1207 8541  817 3546    0    0    0    0]
 [1207 8541  817 2538    0    0    0    0]
 [1207 1521  817 9861    0    0    0    0]
 [3239 7447  715 8917    0    0    0    0]
 [3239 7447 4740 2039    0    0    0    0]]


In [10]:
dim=10

**create** **the model**

In [11]:
model=Sequential()
model.add(Embedding(vsize,10,input_length=sent_length))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


**compile the model**

In [12]:
model.compile('adam','mse')

**summary**

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

**prediction the glass of milk**

In [14]:
embedded_docs[1]
model.predict(embedded_docs[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step


array([[ 0.03860745, -0.01377603, -0.02676063, -0.00708859, -0.02071865,
         0.03096123, -0.01553693,  0.02492697, -0.02467785, -0.04115584],
       [ 0.03562665, -0.00309187,  0.01203232,  0.0419114 ,  0.01407709,
         0.0449378 , -0.01397867, -0.00362289,  0.02578465, -0.00721411],
       [-0.02376438,  0.02428645,  0.00140963, -0.00822283, -0.00585189,
        -0.00026681,  0.02426294,  0.03593104,  0.02272275, -0.00018001],
       [-0.04666612,  0.02040288,  0.00033685,  0.0142359 ,  0.04826595,
        -0.01206486, -0.00590718,  0.02028025,  0.01734158,  0.00898021],
       [-0.01432725,  0.01506002, -0.04803076,  0.00920709,  0.01431743,
         0.03256276,  0.01595166, -0.02586378,  0.01081103, -0.00591158],
       [-0.01432725,  0.01506002, -0.04803076,  0.00920709,  0.01431743,
         0.03256276,  0.01595166, -0.02586378,  0.01081103, -0.00591158],
       [-0.01432725,  0.01506002, -0.04803076,  0.00920709,  0.01431743,
         0.03256276,  0.01595166, -0.02586378

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np



texts = ["Buy now! Limited time offer!",
         "Hello, this is just a friendly reminder...",
         "You've won $1,000,000! Click here to claim your prize!",
         "Meeting agenda for today's conference call."]

labels = [1, 0, 1, 0]


max_words = 1000
max_len = 100
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
X = pad_sequences(sequences, maxlen=max_len)


model = Sequential()
model.add(Embedding(max_words, 64, input_length=max_len))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


X = np.array(X)
labels = np.array(labels)


model.fit(X, labels, epochs=10, batch_size=32, validation_split=0.2)


loss, accuracy = model.evaluate(X, labels)
print("Test Accuracy:", accuracy)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6667 - loss: 0.6227 - val_accuracy: 0.0000e+00 - val_loss: 0.8015
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 0.6667 - loss: 0.5717 - val_accuracy: 0.0000e+00 - val_loss: 0.8207
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.6667 - loss: 0.5245 - val_accuracy: 0.0000e+00 - val_loss: 0.8271
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.4816 - val_accuracy: 0.0000e+00 - val_loss: 0.8260
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 1.0000 - loss: 0.4398 - val_accuracy: 0.0000e+00 - val_loss: 0.8191
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.3987 - val_accuracy: 0.0000e+00 - val_loss: 0.8065
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.3592 - val_accuracy: 0.0000e+00 - val_loss: 0.7897
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 1.0000 - loss: 0.3218 - val_accuracy: 0.000

In [22]:
new_texts = ["Special offer! Buy now and get 50% off!",
             "Congratulations! You've won a free vacation package!",
             "Reminder: Your appointment is tomorrow at 10 AM.","Hello, this is just a friendly reminder..."]

new_sequences = tokenizer.texts_to_sequences(new_texts)
new_X = pad_sequences(new_sequences, maxlen=max_len)


predictions = model.predict(new_X)


for text, pred in zip(new_texts, predictions):
    print(f"Email: {text}")
    print(f"Spam Probability: {pred[0]}")
    if pred[0] > 0.5:
        print("Prediction: Spam")
    else:
        print("Prediction: Not Spam")
    print()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step
Email: Special offer! Buy now and get 50% off!
Spam Probability: 0.616345226764679
Prediction: Spam

Email: Congratulations! You've won a free vacation package!
Spam Probability: 0.6213865280151367
Prediction: Spam

Email: Reminder: Your appointment is tomorrow at 10 AM.
Spam Probability: 0.5988642573356628
Prediction: Spam

Email: Hello, this is just a friendly reminder...
Spam Probability: 0.2390315681695938
Prediction: Not Spam

